// SpiritValers maps.json minimum map levels, verified 2026-10-07.
export const MAP_LEVELS: Readonly<Record<string, number>> = Object.freeze({
  "Dark Fortress": 150,
  "Dark Manor": 145,
  "Starfall Tundra": 131,
  "Turtle Nexus": 131,
  "Night Garden": 126,
  "The Forge": 126,
  "Abyss Castle Library": 121,
  "Goblin Warcamp": 121,
  "Abyss Castle Crypt": 116,
  "Sunken Depths": 101,
  "Demon's Maw": 96,
  "Underground Cavern": 86,
  "Sanctum of Light": 76,
  "Crystal Cave": 71,
  "Swamp Wilderness": 66,
  "Goblin Cave 2": 56,
  "Forgotten Depths 2": 46,
  "Goblin Village": 46,
  "Forgotten Depths 1": 41,
  "Mystic Lake 2": 36,
  "Windy Desert South": 31,
  "Fairy Glen": 31,
  "Windy Desert North": 31,
  "Windy Desert": 26,
  "Festering Woods 2": 21,
  "Bunny Woods": 21,
  "Sunny Meadows 2": 6
});
